name: dyvine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - psutil>=5.9.0
  - setuptools
  - wheel
  - pip:
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.22.0
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - python-dotenv>=1.0.0
    - f2>=0.0.1.7
    - httpx>=0.24.0
    - python-multipart>=0.0.6
    - black>=23.3.0
    - isort>=5.12.0
    - mypy>=1.3.0
    - ruff>=0.0.270
    - pre-commit>=3.3.3
