---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: dyvine-config
data:
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  RATE_LIMIT_PER_SECOND: "10"
  CORS_ORIGINS: "*"
  DOUYIN_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  DOUYIN_REFERER: "https://www.douyin.com/"

---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: dyvine-secrets
type: Opaque
data:
  # Base64 encoded values - replace these with actual encoded values
  SECRET_KEY: ZGVmYXVsdC1zZWNyZXQta2V5LXBsZWFzZS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  API_KEY: ZGVmYXVsdC1hcGkta2V5LXBsZWFzZS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  DOUYIN_COOKIE: ""  # Add your base64 encoded cookie here

---
# Persistent Volume Claim for data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dyvine-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyvine
  labels:
    app: dyvine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dyvine
  template:
    metadata:
      labels:
        app: dyvine
    spec:
      containers:
      - name: dyvine
        image: dyvine:latest  # Replace with your image repository
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        envFrom:
        - configMapRef:
            name: dyvine-config
        - secretRef:
            name: dyvine-secrets
        volumeMounts:
        - name: dyvine-data
          mountPath: /app/data
        - name: dyvine-logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: dyvine-data
        persistentVolumeClaim:
          claimName: dyvine-data-pvc
      - name: dyvine-logs
        emptyDir: {}

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: dyvine
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: dyvine

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dyvine
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
  - host: dyvine.example.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dyvine
            port:
              number: 80
