apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dyvine

resources:
  - ../../base
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

patchesJson6902:
  - target:
      kind: Deployment
      name: dyvine-api
    path: patches.yaml

images:
  - name: ghcr.io/memenow/dyvine
    newTag: latest

configMapGenerator:
  - name: dyvine-config
    behavior: merge
    literals:
      - API_DEBUG=false