apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dyvine-api-pdb
  namespace: dyvine
  labels:
    app.kubernetes.io/name: dyvine
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: dyvine
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: dyvine
      app.kubernetes.io/component: api