apiVersion: v1
kind: Secret
metadata:
  name: dyvine-secrets
  namespace: dyvine
  labels:
    app.kubernetes.io/name: dyvine
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: dyvine
type: Opaque
data:
  # These values will be replaced by actual secrets from GitHub Secrets
  SECURITY_SECRET_KEY: PLACEHOLDER
  SECURITY_API_KEY: PLACEHOLDER
  R2_ACCOUNT_ID: PLACEHOLDER
  R2_ACCESS_KEY_ID: PLACEHOLDER
  R2_SECRET_ACCESS_KEY: PLACEHOLDER
  DOUYIN_COOKIE: PLACEHOLDER