apiVersion: v1
kind: ServiceAccount
metadata:
  name: dyvine-api
  namespace: dyvine
  labels:
    app.kubernetes.io/name: dyvine
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: dyvine
automountServiceAccountToken: false