apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dyvine

resources:
  - core/namespace.yaml
  - core/service-account.yaml
  - core/configmap.yaml
  - core/secret.yaml
  - core/deployment.yaml
  - core/service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: latest